
import sys
import os

path = '/Users/dinurm.pradipta/.gemini/antigravity/scratch/aruneeka-pro/src/components/AruneekaAnalytics.tsx'
with open(path, 'r') as f:
    lines = f.readlines()

keep = []
for line in lines:
    keep.append(line)
    if 'Detailed Asset Breakdown Section' in line:
        break

tail = [
    '        <motion.div \n',
    '           initial={{ opacity: 0, y: 30 }}\n',
    '           animate={{ opacity: 1, y: 0 }}\n',
    '           transition={{ delay: 0.3 }}\n',
    '           className="bg-white rounded-[32px] md:rounded-[40px] shadow-premium p-6 md:p-12 border border-slate-50 relative overflow-hidden"\n',
    '        >\n',
    '           {/* Logic Locking for Breakdown Table */}\n',
    '           {(() => {\n',
    '              const isBreakdownLocked = currentTier === "free" && !isPowerUserActual;\n',
    '              return isBreakdownLocked && (\n',
    '                <div className="absolute inset-0 z-30 flex flex-col items-center justify-center bg-white/5 backdrop-blur-[12px] transition-all duration-700">\n',
    '                   <motion.div \n',
    '                     initial={{ scale: 0.9, opacity: 0 }}\n',
    '                     animate={{ scale: 1, opacity: 1 }}\n',
    '                     className="flex flex-col items-center gap-4 text-center p-12"\n',
    '                   >\n',
    '                      <div className="flex flex-col items-center text-center space-y-4">\n',
    '                          <div className="w-16 h-16 bg-amber-50 rounded-full flex items-center justify-center text-amber-500 shadow-inner">\n',
    '                            <ShieldCheck size={32} />\n',
    '                          </div>\n',
    '                          <div className="space-y-1">\n',
    '                             <h3 className="text-xl font-bold text-slate-800 tracking-tight">Pro Insight Required</h3>\n',
    '                             <p className="text-[10px] text-slate-400 font-medium">Upgrade to view detailed analytics for each individual asset.</p>\n',
    '                          </div>\n',
    '                       </div>\n',
    '                       <button \n',
    '                         onClick={() => openUpgrade()}\n',
    '                         className="mt-2 px-8 py-3 bg-amethyst-primary text-white rounded-xl text-[10px] font-bold shadow-xl shadow-amethyst-primary/20 hover:scale-105 transition-all">\n',
    '                        Upgrade to Unlock\n',
    '                      </button>\n',
    '                   </motion.div>\n',
    '                </div>\n',
    '              );\n',
    '           })()}\n',
    '\n',
    '           <div className={`transition-all duration-700 ${currentTier === "free" && !isPowerUserActual ? "blur-md grayscale opacity-30 select-none" : ""}`}>\n',
    '              <div className="flex items-center justify-between mb-12">\n',
    '                 <h3 className="text-2xl font-black text-amethyst-dark tracking-tight">Detailed Asset Breakdown</h3>\n',
    '                 <div className="flex items-center gap-2">\n',
    '                    <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_8px_rgba(16,185,129,0.5)]"></div>\n',
    '                    <span className="text-[10px] font-black text-slate-300">Live Tracking Data (this month)</span>\n',
    '                 </div>\n',
    '              </div>\n',
    '\n',
    '            <div className="overflow-x-auto custom-scrollbar">\n',
    '               <table className="w-full">\n',
    '                  <thead>\n',
    '                     <tr className="border-b border-slate-50">\n',
    '                        <th className="text-left py-6 px-4 text-[10px] font-black text-slate-300">Content identity</th>\n',
    '                        <th className="text-center py-6 px-4 text-[10px] font-black text-slate-300 uppercase tracking-widest">PIC / Author</th>\n',
    '                        <th className="text-center py-6 px-4 text-[10px] font-black text-slate-300 uppercase tracking-widest">Posting Date</th>\n',
    '                        <th className="text-center py-6 px-4 text-[10px] font-black text-slate-300 uppercase tracking-widest">Views</th>\n',
    '                        <th className="text-center py-6 px-4 text-[10px] font-black text-slate-300 uppercase tracking-widest">ER %</th>\n',
    '                        <th className="text-right py-6 px-4 text-[10px] font-black text-slate-300 uppercase tracking-widest">Action</th>\n',
    '                     </tr>\n',
    '                  </thead>\n',
    '                  <tbody>\n',
    '                     {data.filter((p) => p.status?.toLowerCase() === "uploaded").sort((a, b) => new Date(b.due_date).getTime() - new Date(a.due_date).getTime()).map((item, i) => {\n',
    '                        const m = item.metrics || {};\n',
    '                        const getV = (keys) => {\n',
    '                           const ns = keys.map(k => k.replace(/[\\s_.]/g, "").toLowerCase());\n',
    '                           for (const k in m) if (ns.includes(k.replace(/[\\s_.]/g, "").toLowerCase())) return Number(m[k]) || 0;\n',
    '                           return 0;\n',
    '                        };\n',
    '                        const views = getV(["views", "impressions"]);\n',
    '                        const interactions = getV(["interactions"]) || (getV(["likes"]) + getV(["comments"]) + getV(["shares", "reposts"]) + getV(["saves", "bookmarks"]));\n',
    '                        const er = views > 0 ? ((interactions / views) * 100).toFixed(2) : "0.00";\n',
    '                        const p = item.platform?.toLowerCase() || "";\n',
    '                        return (\n',
    '                           <tr \n',
    '                             key={i} \n',
    '                             onClick={() => openDetail(item)}\n',
    '                             className="group hover:bg-slate-50/80 transition-all border-b border-slate-50 last:border-0 cursor-pointer"\n',
    '                           >\n',
    '                              <td className="py-6 px-4">\n',
    '                                 <div className="flex items-center gap-5">\n',
    '                                    <div className="w-12 h-12 bg-white rounded-2xl border border-slate-100 flex items-center justify-center shadow-sm group-hover:shadow-md transition-all">\n',
    '                                       {p.includes("instagram") ? <img src="https://cdn.simpleicons.org/instagram/E4405F" className="w-5 h-5" /> : \n',
    '                                        p.includes("tiktok") ? <img src="https://cdn.simpleicons.org/tiktok/000000" className="w-5 h-5" /> :\n',
    '                                        p.includes("threads") ? <img src="https://cdn.simpleicons.org/threads/000000" className="w-5 h-5" /> : <Package size={18}/>}\n',
    '                                    </div>\n',
    '                                    <div>\n',
    '                                       <p className="text-sm font-black text-amethyst-dark group-hover:text-amethyst-primary transition-colors leading-tight mb-1">{item.title}</p>\n',
    '                                       <p className="text-[10px] font-bold text-slate-400 italic uppercase tracking-widest">{item.content_pillar || "Insight"}</p>\n',
    '                                    </div>\n',
    '                                 </div>\n',
    '                              </td>\n',
    '                              <td className="py-6 px-4 text-center">\n',
    '                                 <div className="flex flex-col items-center justify-center gap-1">\n',
    '                                    <div className="w-9 h-9 bg-slate-50 rounded-full flex items-center justify-center border border-slate-100 overflow-hidden shadow-inner">\n',
    '                                       {item.author_avatar ? <img src={item.author_avatar} className="w-full h-full object-cover" /> : <div className="text-[10px] font-black text-slate-300">{item.author_name?.charAt(0) || "P"}</div>}\n',
    '                                    </div>\n',
    '                                    <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{item.author_name || "Owner"}</p>\n',
    '                                 </div>\n',
    '                              </td>\n',
    '                              <td className="py-6 px-4 text-center">\n',
    '                                 <p className="text-[11px] font-bold text-slate-500 italic">{new Date(item.due_date).toLocaleDateString("id-ID", { day: "numeric", month: "short", year: "numeric" })}</p>\n',
    '                              </td>\n',
    '                              <td className="py-6 px-4 text-center">\n',
    '                                 <p className="text-sm font-black text-amethyst-dark">{views >= 1000 ? (views/1000).toFixed(1) + "K" : views}</p>\n',
    '                              </td>\n',
    '                              <td className="py-6 px-4 text-center">\n',
    '                                 <div className="flex flex-col items-center gap-1">\n',
    '                                    <p className={`text-sm font-black ${Number(er) > 5 ? "text-emerald-500" : "text-amethyst-primary"}`}>{er}%</p>\n',
    '                                    <div className="w-12 h-1 bg-slate-100 rounded-full overflow-hidden\"><div className={`h-full ${Number(er) > 5 ? "bg-emerald-500" : "bg-amethyst-primary"}`} style={{ width: Math.min(Number(er) * 5, 100) + "%" }}></div></div>\n',
    '                                 </div>\n',
    '                              </td>\n',
    '                              <td className="py-6 px-4">\n',
    '                                 <div className="flex items-center justify-end gap-3">\n',
    '                                    <button onClick={(e) => { e.stopPropagation(); openMetrics(item); }} className="w-10 h-10 bg-amethyst-light/10 text-amethyst-primary rounded-xl flex items-center justify-center hover:bg-amethyst-primary hover:text-white transition-all\"><Activity size={16}/></button>\n',
    '                                    <a href={item.post_link || "#"} target="_blank" rel="noreferrer" className={`w-10 h-10 rounded-xl flex items-center justify-center transition-all ${item.post_link ? "bg-amethyst-dark text-white hover:bg-black" : "bg-slate-50 text-slate-300 cursor-not-allowed\"}`}><ExternalLink size={16}/></a>\n',
    '                                 </div>\n',
    '                              </td>\n',
    '                           </tr>\n',
    '                        );\n',
    '                     })}\n',
    '                  </tbody>\n',
    '               </table>\n',
    '            </div>\n',
    '            </div>\n',
    '         </motion.div>\n',
    '         </>\n',
    '      )}\n',
    '    </div>\n',
    '  );\n',
    '};\n\n',
    'export default AruneekaAnalytics;\n'
]

with open(path, 'w') as f:
    f.writelines(keep + tail)
